title: دفترچه راهنمای زبیکس
description: این دفترچه اطلاعات لازم برای نصب، پیکربندی و اجرای زبیکس نسخه 6.4 در بر می گیرد.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
#site_author: Carlos Pereira Atencio
#repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: false
github_docs_folder: false
sticky_navigation: false
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
